include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart

  errors:
    unused_local_variable: ignore
    unused_element: ignore
    non_constant_identifier_names: ignore
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    unused_field: ignore
    prefer_final_fields: ignore
