workflows:
  android-deploy-workflow:
    name: Android Production Deployment
    instance_type: mac_mini_m1
    max_build_duration: 30
    triggering:
      events:
        - tag
      cancel_previous_builds: true
    environment:
      groups:
        - google_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup the keystore
        script: |
          echo $KEYSTORE_FILE | base64 --decode > /tmp/keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_KEY_PASSWORD
          keyAlias=upload
          storeFile=/tmp/keystore.jks
          EOF
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build AAB
        script: |
          cd $CM_BUILD_DIR
          flutter build appbundle --build-number=$PROJECT_BUILD_NUMBER
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          flutter build apk --release --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal
        submit_as_draft: true
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - google_credentials
      vars:
        FIREBASE_PROJECT: "customer-maxx-crm"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Run tests
        script: |
          flutter test
      - name: Run code analysis
        script: |
          flutter analyze
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
  ios-production-workflow:
    name: iOS Production Deployment
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - appstore_credentials
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Run tests
        script: |
          flutter test
      - name: Set up signing
        script: |
          # Set up code signing
          keychain initialize
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: |
          flutter build ipa --release --build-number=$(date +%s)
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false