name: customer_maxx_crm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.5
  csv: ^6.0.0
  file_picker: ^10.3.3
  syncfusion_flutter_charts: ^31.1.23
  table_calendar: ^3.1.2
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  material_table_view: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/docs_images/